### ISSUE TITLE
Could you provide the elapsed time it takes to complete the learning or sec/epoch for each models ResNet-v1-50, OctResNet-v1-50?

### ISSUE THREAD

**Issue by sweaterr** [terrychenism/OctaveConv#3]
Hi, and thks for this repo

I want to know if octConv is really fast than vanila conv on general Gpu environment

Could you provide the elapsed time it takes to complete the learning or sec/epoch for each models ResNet-v1-50, OctResNet-v1-50?

**Comment by giorking** [comment]
@sweaterr You may uncomment these few lines  to get the speed here: [https://github.com/terrychenism/OctaveConv/blob/master/test_octConv.py#L36](url)

On the other hand, here is the screen shot for your reference:
![mmexport1555535874008](https://user-images.githubusercontent.com/5257424/56321606-f2fa1e00-611b-11e9-9e38-d061c71e1857.jpg)

**Comment by nick-onedrop** [comment]
@giorking Could you please tell me what kind of GPU you used to get the above result?

**Comment by giorking** [comment]
@pizpaz1 V100

**Comment by sweaterr** [comment]
Thanks for your reply. 👍
